package dev.autumn.sandbox
import dev.autumn.annotations.LongLived

import dev.autumn.annotations.ColdChannel
import dev.autumn.annotations.HotPath
import dev.autumn.annotations.NetworkChannel
import dev.autumn.annotations.Pipelined
import dev.autumn.annotations.RegisterChannel
import dev.autumn.annotations.ThreadCacheBudget
import dev.autumn.channel.AutumnChannel

// 1. Automated SoA Generation target
@Pipelined(capacity = 64)
interface OrderEvent {
    var orderId: Long
    var quantity: Int
    var side: Byte
}

/**
 * GENERATED BY: FlyweightDeclarationGenerator in the K2 Compiler Phase.
 * Devs don't write this; the compiler makes it available automatically.
 */
@JvmInline
value class OrderEventFlyweight(val index: Int) : OrderEvent {
    override var orderId: Long
        get() = 0L // IR Rewrites this
        set(value) {} // IR Rewrites this

    override var quantity: Int
        get() = 0 // IR Rewrites this
        set(value) {} // IR Rewrites this

    override var side: Byte
        get() = 0 // IR Rewrites this
        set(value) {} // IR Rewrites this
}


// 2. Hardware mapping and constraint definitions
@LongLived
class HighFrequencyTradingNode {

    // ✅ ALLOWED: Direct DMA ingress from the NIC via epoll/io_uring
    @NetworkChannel(capacity = 4096)
    val marketDataIngress: Any? = null

    // ✅ ALLOWED: L1-speed queue passing data between pinned cores 
    @RegisterChannel(size = 1024)
    val coreToCoreQueue: Any? = null

    // ✅ ALLOWED: Queue capturing history internally before flushing
    @RegisterChannel(size = 1024)
    val auditLogQueue = AutumnChannel<OrderEvent>(1024)
    
    // ✅ ALLOWED: Background telemetry dropping data to NVMe
    @ColdChannel
    val slowDiskWriterQueue = AutumnChannel<OrderEvent>(1024)

    // ❌ ERROR: Contradictory architectural definitions 
    // UNCOMMENT TO TRIGGER COMPILER ERROR ([Autumn] Architectural contradiction: A property cannot be both a @ColdChannel and a @RegisterChannel/@NetworkChannel)
    // @ColdChannel
    // @RegisterChannel
    // val impossibleQueue: Any? = null

    // ❌ ERROR: RegisterChannel wait-free modulo mathematics strictly require Power of 2 sizes
    // UNCOMMENT TO TRIGGER COMPILER ERROR ([Autumn] @RegisterChannel capacity must be exactly a Power of Two)
    // @RegisterChannel(size = 1000)
    // val misalignedQueue: Any? = null

    @HotPath
    @ThreadCacheBudget(32768)
    fun processMarketData() {
        // Poll for a valid array slot index (Zero-Allocation)
        val idx = auditLogQueue.buffer.offer()
        if (idx == -1) return // Backpressure applied
        
        // Instantate the Flyweight Wrapper (Inline Value Class erases to an Int!)
        val order = OrderEventFlyweight(idx)
        
        // 1. SoA Write (Setter Interception extracts the order.index parameter implicitly!)
        order.quantity = 100
        order.side = 1

        // 2. SoA Read (Getter Interception)
        if (order.quantity > 50) {
            val tick = coreToCoreQueue
        }
        
        // Commit the index across the ring buffer
        auditLogQueue.buffer.commitOffer()
        
        // ❌ ERROR: Accessing a @ColdChannel inside a @HotPath triggers L1 cache eviction protection!
        // UNCOMMENT TO TRIGGER COMPILER ERROR ([Autumn] Illegal @ColdChannel usage inside a @HotPath.)
        // val forbiddenRead = slowDiskWriterQueue
    }
}
