name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install libbpf
      run: sudo apt-get update && sudo apt-get install -y libbpf-dev

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Publish Compiler Plugin to Maven Local
      run: ./gradlew :autumn-compiler-plugin:publishToMavenLocal
    - name: Build and Test
      run: ./gradlew koverXmlReport build
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./build/reports/kover/report.xml
        token: ${{ secrets.CODECOV_TOKEN }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
    - name: Install libbpf
      run: sudo apt-get update && sudo apt-get install -y libbpf-dev

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Publish Compiler Plugin to Maven Local
      run: ./gradlew :autumn-compiler-plugin:publishToMavenLocal
    - name: Prepare Cryptographic Key and Trim Credentials
      env:
        RAW_USER: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        RAW_PASS: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "ORG_GRADLE_PROJECT_signingInMemoryKey<<$EOF" >> "$GITHUB_ENV"
        echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 -d >> "$GITHUB_ENV"
        echo "" >> "$GITHUB_ENV"
        echo "$EOF" >> "$GITHUB_ENV"
        
        # Safely trim whitespaces that are commonly copied from the Sonatype UI
        CLEAN_USER=$(printf "%s" "$RAW_USER" | tr -d '[:space:]')
        CLEAN_PASS=$(printf "%s" "$RAW_PASS" | tr -d '[:space:]')
        echo "Token Username Length: ${#CLEAN_USER}"
        echo "Token Password Length: ${#CLEAN_PASS}"
        if [ -z "$CLEAN_USER" ]; then echo "::error::MAVEN_CENTRAL_USERNAME is empty! Please check Github Secrets."; exit 1; fi
        echo "ORG_GRADLE_PROJECT_mavenCentralUsername=$CLEAN_USER" >> "$GITHUB_ENV"
        echo "ORG_GRADLE_PROJECT_mavenCentralPassword=$CLEAN_PASS" >> "$GITHUB_ENV"
    - name: Publish to Sonatype Maven Central
      run: ./gradlew publishAndReleaseToMavenCentral
      env:
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
