name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Publish Compiler Plugin to Maven Local
      run: ./gradlew :autumn-compiler-plugin:publishToMavenLocal

    - name: Build and Test
      run: ./gradlew koverXmlReport build

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./build/reports/kover/report.xml
        token: ${{ secrets.CODECOV_TOKEN }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Publish Compiler Plugin to Maven Local
      run: ./gradlew :autumn-compiler-plugin:publishToMavenLocal

    - name: Publish to Sonatype Maven Central
      run: |
        echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 -d > secring.gpg
        export ORG_GRADLE_PROJECT_signingSecretKeyFile="$PWD/secring.gpg"
        ./gradlew publishAndReleaseToMavenCentral
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
